export const DAILY_TASK_LIMIT = 3;

export const START_ACTIVITY_META = {
  pve:{ label:'PvE Combat', group:'Combat', link:'/activities/#combat' },
  pvp:{ label:'PvP', group:'Combat', link:'/pvp/' },
  ax:{ label:'Anti-Xeno', group:'Combat', link:'/activities/#ax' },
  surface:{ label:'Surface Operations', group:'Combat', link:'/guides/operations/' },
  mining:{ label:'Mining', group:'Industry & Logistics', link:'/guides/mining/' },
  trade:{ label:'Trade & Hauling', group:'Industry & Logistics', link:'/trading/' },
  'carrier-logistics':{ label:'Carrier Logistics', group:'Industry & Logistics', link:'/carriers/' },
  engineering:{ label:'Engineering & Shipbuilding', group:'Industry & Logistics', link:'/guides/engineering/' },
  exploration:{ label:'Exploration', group:'Exploration & Discovery', link:'/activities/#exploration' },
  exobiology:{ label:'Exobiology', group:'Exploration & Discovery', link:'/activities/#exploration' },
  bgs:{ label:'Background Simulation', group:'Galaxy & Frontier', link:'/operations/#daily-orders' },
  colonization:{ label:'Colonization', group:'Galaxy & Frontier', link:'/projects/' },
  powerplay:{ label:'Powerplay', group:'Galaxy & Frontier', link:'/activities/#powerplay' },
  operations:{ label:'Squad Operations', group:'Galaxy & Frontier', link:'/operations/#daily-orders' },
};

const ALL = ['new','some','comfortable','experienced'];
const DEV_PLUS = ['some','comfortable','experienced'];
const EXP_PLUS = ['comfortable','experienced'];
const VET = ['experienced'];
const NEW_DEV = ['new','some'];

const task = (id, title, objective, levels = ALL, kind = 'activity', style = 'any', link = '') => ({ id,title,objective,levels,kind,style,link });

export const START_TASKS = {
  pve:[
    task('pve-bounties-10','Bounty warm-up','Destroy 10 wanted ships and cash the vouchers without losing your ship.',ALL,'activity'),
    task('pve-missions-3','Three-job combat run','Complete three combat missions for the same session and return to port.',ALL,'activity'),
    task('pve-res-session','Resource-site patrol','Spend 15 minutes fighting wanted ships in a Resource Extraction Site, then leave before greed turns it into a rebuy.',ALL,'activity'),
    task('pve-module-target','Shoot something important','Destroy at least three hostile ships after deliberately targeting a useful subsystem instead of only shooting the hull.',DEV_PLUS,'challenge'),
    task('pve-fixed-session','Fixed-weapon practice','Spend one combat session using at least one fixed weapon and focus on keeping good firing solutions.',DEV_PLUS,'challenge'),
    task('pve-hazres','HazRES pressure test','Spend 20 minutes in a Hazardous Resource Extraction Site and leave on your own terms.',EXP_PLUS,'challenge'),
    task('pve-wing-hunt','Wing bounty hunt','Join another Mongrel for a bounty-hunting session and practice target focus instead of splitting damage.',DEV_PLUS,'challenge','group'),
    task('pve-teach','Combat coach','Take a less-experienced Mongrel into PvE and teach one practical skill they can demonstrate before the session ends.',VET,'challenge','group'),
  ],
  pvp:[
    task('pvp-escape-drill','Interdiction escape drill','Practice submitting, boosting, evasive flying, and high-waking with a willing squadmate until the sequence feels automatic.',NEW_DEV,'challenge','group'),
    task('pvp-duels-3','Three friendly duels','Fight three rebuy-safe friendly duels and identify one mistake you repeated.',ALL,'activity','group'),
    task('pvp-pips','PvP pip drill','Run several short friendly rounds where your main goal is deliberate SYS/ENG/WEP management instead of winning.',ALL,'challenge','group'),
    task('pvp-fixed-accuracy','Fixed-weapon accuracy','Spend a duel session focusing on fixed-weapon hit rate rather than winning the fight.',DEV_PLUS,'challenge','group'),
    task('pvp-range-control','Control the range','Run several short duels where your only goal is to hold the engagement range you chose.',DEV_PLUS,'challenge','group'),
    task('pvp-defense','Survival round','Fight a stronger or more experienced pilot and make survival, disengagement, and recovery the objective.',EXP_PLUS,'challenge','group'),
    task('pvp-wing','Wing-fight night','Join a coordinated friendly wing fight and practice calls, focus fire, and staying with your team.',EXP_PLUS,'challenge','group'),
    task('pvp-coach','Teach one PvP fundamental','Coach another Mongrel through one PvP fundamental and keep drilling it until they improve measurably.',VET,'challenge','group'),
  ],
  ax:[
    task('ax-scouts-10','Scout sweep','Destroy 10 Thargoid Scouts in one session and return alive.',ALL,'activity'),
    task('ax-threat4','Clear a Scout pack','Clear a Threat 4 Non-Human Signal Source and return to port.',ALL,'activity'),
    task('ax-nhss-recon','NHSS reconnaissance','Find a Non-Human Signal Source yourself, enter it, identify what is there, and leave alive after completing a sensible objective for your current skill.',ALL,'activity'),
    task('ax-gauss-scouts','Gauss aim practice','Destroy at least three Scouts primarily with Guardian Gauss or another precision AX weapon.',DEV_PLUS,'challenge'),
    task('ax-cyclops','Cyclops hunt','Destroy a Cyclops Interceptor and return alive.',DEV_PLUS,'challenge'),
    task('ax-basilisk','Basilisk hunt','Destroy a Basilisk Interceptor and return alive.',EXP_PLUS,'challenge'),
    task('ax-wing-cz','AX wing operation','Join a wing and contribute through a complete AX conflict-zone objective when one is available.',EXP_PLUS,'challenge','group'),
    task('ax-mentor','Bring a Mongrel into AX','Help a less-experienced Mongrel complete a meaningful AX objective without simply carrying the fight for them.',VET,'challenge','group'),
  ],
  surface:[
    task('surface-missions-3','Three boots-on-ground jobs','Complete three on-foot missions in one session.',ALL,'activity'),
    task('surface-loot','Clean extraction','Complete an on-foot mission, collect useful materials along the way, and leave without dying.',ALL,'activity'),
    task('surface-one-settlement','One complete settlement run','Choose one settlement mission you understand, complete the objective from insertion through extraction, and return to port.',ALL,'activity'),
    task('surface-stealth','Quiet approach','Complete a settlement objective while avoiding unnecessary alarms and firefights.',DEV_PLUS,'challenge'),
    task('surface-gcz','Ground CZ run','Complete a ground conflict zone from deployment through final result.',DEV_PLUS,'activity'),
    task('surface-reactivation','Settlement reactivation','Complete a settlement reactivation or restoration-style operation.',DEV_PLUS,'challenge'),
    task('surface-team','Surface team operation','Run a coordinated surface mission with another Mongrel and divide roles before insertion.',EXP_PLUS,'challenge','group'),
    task('surface-coach','Teach settlement work','Take a newer player through a settlement operation and teach access, threat, and extraction habits.',VET,'challenge','group'),
  ],
  mining:[
    task('mining-100t','Fill 100 tonnes','Mine and sell at least 100 tonnes of your chosen commodity.',ALL,'activity'),
    task('mining-full-loop','Complete the whole loop','Start empty, locate a site, mine, refine/collect, travel to market, and sell the haul in one session.',ALL,'activity'),
    task('mining-method','Change the routine','Use a mining method or commodity you do not normally choose and complete a full gather-to-sell loop.',ALL,'challenge'),
    task('mining-core-5','Crack five cores','Find and successfully crack five core asteroids.',DEV_PLUS,'challenge'),
    task('mining-laser-200','Two-hundred-tonne laser run','Mine and sell at least 200 tonnes using laser mining.',DEV_PLUS,'challenge'),
    task('mining-new-site','Scout somewhere new','Try a mining location you have not used recently and decide whether you would return.',EXP_PLUS,'challenge'),
    task('mining-supply','Mine for a purpose','Choose a commodity needed by a current project, carrier, or squad goal and deliver a useful load.',EXP_PLUS,'challenge'),
    task('mining-mentor','Teach a full mining loop','Take another Mongrel from outfitting/site choice through sale and explain the decisions instead of only leading the way.',VET,'challenge','group'),
  ],
  trade:[
    task('trade-500t','Move 500 tonnes','Complete a profitable haul totaling at least 500 tonnes.',ALL,'activity'),
    task('trade-3legs','Three-leg trader','Complete three profitable station-to-station trade legs without using the same destination twice.',ALL,'activity'),
    task('trade-new-cargo','Haul something different','Choose a legal commodity you do not normally trade, find a profitable source/destination pair, and complete a successful run.',ALL,'challenge'),
    task('trade-medium','Medium-pad logistics','Run a profitable trade session using a medium-pad ship.',DEV_PLUS,'challenge'),
    task('trade-5m','Five-million-profit session','Earn at least 5 million credits in trade profit during one session.',DEV_PLUS,'challenge'),
    task('trade-fast-loop','Build a fast loop','Find or design a repeatable trade loop and complete three cycles while tracking turnaround time.',EXP_PLUS,'challenge'),
    task('trade-carrier','Carrier support haul','Load or unload at least 1,000 tonnes for a carrier or squad logistics objective.',EXP_PLUS,'challenge','group'),
    task('trade-coordinate','Coordinate the haulers','Organize a small hauling effort with at least one other Mongrel and divide the workload.',VET,'challenge','group'),
  ],
  'carrier-logistics':[
    task('carrier-tritium-500','Tritium top-up','Deliver at least 500 tonnes of Tritium to a carrier that can use it.',ALL,'activity'),
    task('carrier-load-1000','Load a thousand','Load at least 1,000 tonnes of cargo onto a carrier.',ALL,'activity'),
    task('carrier-unload-1000','Unload a thousand','Unload at least 1,000 tonnes from a carrier to the intended destination.',ALL,'activity'),
    task('carrier-route','Plan a carrier move','Plan a multi-jump carrier route including fuel needs and a reasonable contingency reserve.',DEV_PLUS,'challenge'),
    task('carrier-scout','Scout the destination','Scout a proposed carrier destination and verify useful nearby services or operational constraints.',DEV_PLUS,'challenge'),
    task('carrier-two-haulers','Two-hauler logistics','Coordinate a carrier load/unload with at least one other Commander and keep the flow organized.',EXP_PLUS,'challenge','group'),
    task('carrier-lead','Lead a carrier operation','Plan and run a small carrier logistics operation from objective through completion.',VET,'challenge','group'),
  ],
  engineering:[
    task('eng-one-module','Improve one real module','Choose one important module on a ship you actually fly and complete a meaningful engineering upgrade.',ALL,'activity'),
    task('eng-materials','Restock one material family','Pick Raw, Manufactured, or Encoded materials and deliberately improve your useful stock.',ALL,'activity'),
    task('eng-g3','Take something to Grade 3','Engineer one useful module to at least Grade 3 and understand why you chose that blueprint.',NEW_DEV,'activity'),
    task('eng-experimental','Choose an experimental','Add or change one experimental effect because you understand the tradeoff, not because a build list told you to.',DEV_PLUS,'challenge'),
    task('eng-build-plan','Engineer on paper first','Create a complete engineering plan for one ship before visiting any Engineer, including experimentals and power priorities.',EXP_PLUS,'challenge'),
    task('eng-compare','Compare two valid choices','Pick one module where two engineering approaches are plausible and explain which one better suits the ship’s role.',EXP_PLUS,'challenge'),
    task('eng-review','Review another build','Help another Mongrel improve a build by explaining priorities and tradeoffs instead of handing them a replacement list.',VET,'challenge','group'),
  ],
  exploration:[
    task('explore-500ly','Leave the neighborhood','Travel at least 500 light-years from your starting point and return with exploration data.',ALL,'activity'),
    task('explore-map5','Map five worlds','Fully map five bodies worth mapping during one session.',ALL,'activity'),
    task('explore-fss10','Ten-system survey','Fully FSS-scan ten systems you pass through instead of only honking and moving on.',ALL,'activity'),
    task('explore-new-system','Find something untouched','Visit systems off the obvious route and try to earn a first-discovery or first-mapping tag.',DEV_PLUS,'challenge'),
    task('explore-neutron','Use the neutron highway','Complete a route that includes at least three neutron supercharges and return safely.',DEV_PLUS,'challenge'),
    task('explore-2000ly','Two-thousand-light-year loop','Plan and complete an exploration loop of at least 2,000 light-years.',EXP_PLUS,'challenge'),
    task('explore-unusual','Find an unusual destination','Choose an unusual stellar, planetary, or regional target and navigate there without following a pre-written expedition route.',EXP_PLUS,'challenge'),
    task('explore-lead','Lead a mini expedition','Pick a destination and lead at least one other Mongrel on a short exploration outing.',VET,'challenge','group'),
  ],
  exobiology:[
    task('exo-three-species','Sample three species','Complete genetic samples for three different biological species.',ALL,'activity'),
    task('exo-first-footfall','Find your own biology','Look for an unexplored or lightly traveled body, earn first footfall if possible, and complete at least one sample.',ALL,'activity'),
    task('exo-one-body','Work one biological world','Choose one body with multiple biological signals and complete samples for at least two species there.',ALL,'activity'),
    task('exo-five-scans','Five complete samples','Complete five biological samples in one session.',DEV_PLUS,'challenge'),
    task('exo-value-run','High-value bio hunt','Deliberately target higher-value biological possibilities and complete at least three samples.',DEV_PLUS,'challenge'),
    task('exo-route','Build an exobiology route','Plan a short multi-system route around biological prospects instead of sampling only what you stumble across.',EXP_PLUS,'challenge'),
    task('exo-combined','Explore and sample','Complete a session where exploration mapping and exobiology are both meaningful parts of the route.',EXP_PLUS,'challenge'),
    task('exo-teach','Teach field technique','Take another Mongrel exobiology hunting and teach efficient planet selection, landing, and sample spacing.',VET,'challenge','group'),
  ],
  bgs:[
    task('bgs-read-orders','Work one real Daily Order','Open current Daily Orders, choose one posted BGS objective that matches your skills, and complete a meaningful contribution without freelancing against the plan.',ALL,'activity'),
    task('bgs-predict','Predict the tick','Pick one priority system, review its state/influence/objective, and decide what you expect the next tick to do before checking leadership guidance.',ALL,'challenge'),
    task('bgs-observe','Read before you push','Open Mission Control, choose one tracked system, and identify its influence band, state, alerts, and current objective before doing any BGS work.',ALL,'activity'),
    task('bgs-inf','Mission-INF contribution','If current Daily Orders call for mission support, complete roughly 15 INF worth of missions for the specified faction and stop there.',DEV_PLUS,'activity'),
    task('bgs-bounties','Voucher contribution','If current Daily Orders call for bounty support, redeem roughly 10M Cr in bounty vouchers for the specified beneficiary.',DEV_PLUS,'activity'),
    task('bgs-mixed','Mixed-lever BGS run','For a current raise objective, use two approved positive levers instead of grinding only one, then stop and let the tick measure the result.',EXP_PLUS,'challenge'),
    task('bgs-diagnose','Diagnose before acting','Choose one system outside its desired band and explain which factions/states are locked or sensitive before you do any work.',EXP_PLUS,'challenge'),
    task('bgs-brief','Brief another Mongrel','Explain one live BGS objective to another member, including what to do, what to avoid, and when to stop.',VET,'challenge','group'),
  ],
  colonization:[
    task('colony-haul500','Construction haul','Deliver at least 500 tonnes toward an active construction or colony logistics need.',ALL,'activity'),
    task('colony-three-runs','Three construction runs','Complete three cargo runs to or from a colony/construction site.',ALL,'activity'),
    task('colony-visit','Visit the frontier','Visit an active Mongrel colony or construction project, inspect what is being built, and complete at least one useful support run.',ALL,'activity'),
    task('colony-tour','Inspect a developing system','Visit a current colony system and inspect several sites/stations to understand how its layout and economies are developing.',DEV_PLUS,'activity'),
    task('colony-supply','Supply a real build','Choose an active project requirement and deliver a useful quantity of one needed commodity.',DEV_PLUS,'challenge'),
    task('colony-plan','Plan the logistics','Take one construction requirement and estimate shiploads, pad constraints, source market, and carrier usefulness before hauling.',EXP_PLUS,'challenge'),
    task('colony-carrier','Carrier construction support','Use or support a fleet carrier as part of a meaningful colony construction haul.',EXP_PLUS,'challenge','group'),
    task('colony-coordinate','Coordinate a build push','Organize at least one other Mongrel around a construction/logistics objective and keep the effort focused on the actual requirement.',VET,'challenge','group'),
  ],
  powerplay:[
    task('pp-review','Choose one Powerplay activity','Review the current Powerplay options available to you and complete one activity you already understand.',ALL,'activity'),
    task('pp-learn-one','Learn one mechanic','Pick one Powerplay mechanic you do not fully understand, research it, then perform the related activity once.',ALL,'challenge'),
    task('pp-short-session','Thirty-minute Powerplay session','Choose a Powerplay activity appropriate to your current allegiance and spend about 30 focused minutes doing it before reassessing.',ALL,'activity'),
    task('pp-merits','Complete a merit session','Set a modest personal merit target and complete it without turning the session into an all-night grind.',DEV_PLUS,'activity'),
    task('pp-route','Plan before committing','Compare two possible Powerplay activities and choose the one that best fits your ship, location, and available time.',DEV_PLUS,'challenge'),
    task('pp-efficient','Efficiency test','Repeat one Powerplay activity several times and improve your turnaround or execution between the first and last run.',EXP_PLUS,'challenge'),
    task('pp-wing','Powerplay with a wing','Complete a Powerplay session with another Commander and coordinate the activity rather than simply flying nearby.',EXP_PLUS,'challenge','group'),
    task('pp-teach','Teach one Powerplay loop','Teach another Mongrel one Powerplay activity you know well and have them complete it independently.',VET,'challenge','group'),
  ],
  operations:[
    task('ops-daily','Take a Daily Order','Open current Daily Orders and complete one task that genuinely matches your skills.',ALL,'activity'),
    task('ops-help','Answer a help request','Look for a Mongrel who needs a wingmate, logistics help, build advice, or another practical assist and spend part of the session helping them.',ALL,'activity','group'),
    task('ops-briefing','Check the board before flying','Review Daily Orders, Projects, and Carrier Coordination, then choose the one current squad need where your available ship and time can actually help.',ALL,'activity'),
    task('ops-report','Close the loop','Complete a squad task and clearly report what you did and the useful result instead of disappearing after the work.',DEV_PLUS,'challenge'),
    task('ops-cross-skill','Support outside your default','Choose a current squad objective that uses a secondary skill instead of your normal specialty.',DEV_PLUS,'challenge'),
    task('ops-wing','Join a coordinated operation','Join a Mongrel wing/team activity and follow the agreed objective through completion.',EXP_PLUS,'challenge','group'),
    task('ops-lead','Lead a small operation','Turn one current squad need into a simple brief, gather at least one other member, and lead the work to a clear stopping point.',VET,'challenge','group'),
    task('ops-mentor','Grow another Mongrel','Spend a session helping another member become independently better at one activity useful to the squad.',VET,'challenge','group'),
  ],
};

const START_TASK_ADDITIONS = {
  pve:[
    task('pve-scan-first','Confirm before firing','Spend a combat session deliberately scanning every target and confirming Wanted status before opening fire.',ALL,'activity'),
    task('pve-lowres-clean','Clean LowRES patrol','Spend 20 minutes in a Low Resource Extraction Site and finish the session without fines, accidental friendly fire, or a rebuy.',ALL,'activity'),
    task('pve-chaff-timing','Time your chaff','Fight several gimbal-heavy NPCs and practice using chaff when they actually have a firing solution instead of firing it on cooldown.',ALL,'challenge'),
    task('pve-escape-threshold','Leave before the rebuy','Pick a hull or shield threshold before entering combat and disengage successfully when you reach it.',ALL,'challenge'),
    task('pve-one-mission-clean','One clean assassination','Complete a combat mission from target identification through turn-in without unnecessary extra fights.',ALL,'activity'),
    task('pve-threat-read','Read the threat first','Before accepting three combat missions, compare their threat, target, location, and likely opposition and choose deliberately.',ALL,'challenge'),
    task('pve-subsystem-fsd','Stop the runner','Disable or destroy the FSD or drives on three hostile ships that try to escape.',ALL,'challenge'),
    task('pve-pip-swap','Three-mode pip drill','In one combat session deliberately switch between a defensive pip setup, a maneuvering setup, and a firing setup instead of leaving pips fixed.',DEV_PLUS,'challenge'),
    task('pve-no-joust','Break the joust','Fight several agile NPCs while deliberately using lateral or vertical thrust to avoid repeated head-on passes.',DEV_PLUS,'challenge'),
    task('pve-multitarget','Manage two threats','Take a fight with multiple hostile ships and practice choosing one priority target while keeping awareness of the others.',DEV_PLUS,'challenge'),
    task('pve-high-threat-mission','High-threat mission test','Complete a combat mission that is meaningfully harder than your normal routine and write down what almost went wrong.',EXP_PLUS,'challenge'),
    task('pve-build-test','Test one build change','Change one combat module or engineering choice, run a controlled combat session, and decide whether the change actually improved the ship.',EXP_PLUS,'challenge'),
    task('pve-lead-wing','Lead a PvE wing','Choose targets, make the calls, and lead at least one other Mongrel through a complete bounty or mission session.',VET,'challenge','group'),
  ],
  pvp:[
    task('pvp-blue-zone','Blue-zone turn drill','Use a willing squadmate to practice keeping your ship in its best turning range while tracking them through repeated passes.',ALL,'challenge','group'),
    task('pvp-highwake','High-wake under pressure','Practice selecting a destination, surviving the spool-up, and high-waking while a squadmate actively pressures you.',ALL,'challenge','group'),
    task('pvp-interdict-defense','Defend three interdictions','Have a squadmate interdict you three times and practice winning the tether or deliberately submitting when escape is not the plan.',ALL,'challenge','group'),
    task('pvp-interdict-attack','Interdict three times','Practice establishing three clean interdictions on a willing squadmate from different approach geometries.',ALL,'challenge','group'),
    task('pvp-boost-control','Boost without overshooting','Run a duel drill where the main objective is using boost to change vector without repeatedly flying past the opponent.',ALL,'challenge','group'),
    task('pvp-debrief','One-fight debrief','After a friendly duel, identify one positioning mistake, one pip mistake, and one good decision before fighting again.',ALL,'challenge','group'),
    task('pvp-survive-60','Survive sixty seconds','Against a stronger pilot, make the entire goal surviving for sixty seconds while maintaining useful movement and pips.',ALL,'challenge','group'),
    task('pvp-boost-bleed','Boost-bleed practice','Use friendly drills to combine boost with lateral, vertical, or reverse thrust so the boost changes your vector instead of only adding forward speed.',DEV_PLUS,'challenge','group'),
    task('pvp-preturn','Pre-turn drill','Practice beginning your turn before the pass is fully complete and compare the result with waiting for the opponent to be behind you.',DEV_PLUS,'challenge','group'),
    task('pvp-gear-cap','Boost-cap drill','With a willing squadmate, practice using cargo scoop or landing gear after a boost to control overshoot and stay close.',DEV_PLUS,'challenge','group'),
    task('pvp-faoff-orbit','FA-Off orbit drill','Hold a controlled FA-Off orbit around a cooperative target while keeping guns on target and managing distance.',EXP_PLUS,'challenge','group'),
    task('pvp-counterbuild','Counter one loadout','Fight the same opponent twice, change one tactical or outfitting choice between rounds, and explain why the adjustment helped or failed.',EXP_PLUS,'challenge','group'),
    task('pvp-wing-caller','Call a wing fight','Lead target calls and disengagement calls in a friendly wing engagement rather than focusing only on your own duel.',VET,'challenge','group'),
  ],
  ax:[
    task('ax-scout-scan','Identify before shooting','Enter an NHSS, identify the Thargoid contacts present, and choose an objective appropriate to your ship before committing.',ALL,'activity'),
    task('ax-cold-20','Hold cold for thirty seconds','Against a suitable Thargoid target, practice staying below 20% heat for thirty continuous seconds while maintaining useful movement.',ALL,'challenge'),
    task('ax-caustic-drill','Practice caustic removal','Deliberately rehearse your ship’s chosen caustic-removal method so you can perform it without searching menus during a real fight.',ALL,'challenge'),
    task('ax-shutdown-timing','Shutdown neutralizer timing','Practice timing a Shutdown Field Neutraliser against a real or controlled shutdown pulse opportunity and note the SYS cost.',ALL,'challenge'),
    task('ax-flak-basics','Flak basics','Use Remote Release Flak against a Thargon swarm and focus on learning range and detonation timing rather than total kills.',ALL,'challenge'),
    task('ax-heart-observe','Watch one full heart cycle','Fight or accompany an Interceptor engagement and deliberately identify exertion, heart destruction, shield phase, and the next attack cycle.',ALL,'activity'),
    task('ax-repair-cycle','Repair and re-engage','During an AX session, disengage safely, perform needed repair/synthesis, and re-enter the fight instead of staying committed until failure.',ALL,'challenge'),
    task('ax-cyclops-clean','Clean Cyclops cycle','Destroy a Cyclops while deliberately managing heat, range, and the post-heart phase rather than brute-forcing the fight.',DEV_PLUS,'challenge'),
    task('ax-swarm-first','Swarm-first practice','In an Interceptor fight, make swarm control the primary objective for one full cycle before returning to the heart.',DEV_PLUS,'challenge'),
    task('ax-gauss-groups','Split Gauss groups','Configure and use alternating precision-weapon firegroups to reduce heat spikes during an Interceptor attack run.',DEV_PLUS,'challenge'),
    task('ax-basilisk-cycle','Basilisk cycle practice','Complete a Basilisk heart cycle while deliberately managing its speed advantage and your disengagement route.',EXP_PLUS,'challenge'),
    task('ax-medusa-team','Medusa team run','Join a coordinated Medusa engagement and perform a defined role through the complete kill.',EXP_PLUS,'challenge','group'),
    task('ax-lead-interceptor','Lead an Interceptor kill','Brief the plan, assign roles, and lead at least one other Mongrel through a complete Interceptor engagement.',VET,'challenge','group'),
  ],
  surface:[
    task('surface-terminal','Use the terminal first','At a settlement, use terminals to locate the objective, key buildings, and useful access points before wandering in.',ALL,'activity'),
    task('surface-profile','Profile scan discipline','Complete a settlement visit while deliberately using profile scanning only when it serves the objective and avoiding unnecessary legal trouble.',ALL,'challenge'),
    task('surface-srv-insertion','SRV insertion','Approach a settlement by SRV, choose a sensible parking point, complete an objective, and extract back to the vehicle.',ALL,'activity'),
    task('surface-power-map','Find the power center','At a settlement, locate the power building, access routes, and alarm controls even if the mission does not require using them.',ALL,'challenge'),
    task('surface-one-alarm','Avoid the alarm','Complete a settlement objective without triggering the settlement-wide alarm.',ALL,'challenge'),
    task('surface-material-sort','Loot with a plan','Collect only materials useful to a specific upgrade or unlock instead of filling storage with random items.',ALL,'activity'),
    task('surface-exfil','Plan the exit first','Before entering a hostile or restricted settlement area, choose an extraction route and actually use it when things go wrong.',ALL,'challenge'),
    task('surface-clone-route','Access route drill','Complete a mission that requires restricted access and deliberately plan how you will obtain and use the required clearance.',DEV_PLUS,'challenge'),
    task('surface-disable-alarm','Disable alarms cleanly','Reach and disable settlement alarms without turning the entire site into an uncontrolled firefight.',DEV_PLUS,'challenge'),
    task('surface-restore-fast','Efficient restoration','Complete a restoration/reactivation mission while minimizing unnecessary building-to-building backtracking.',DEV_PLUS,'challenge'),
    task('surface-highsec','High-security infiltration','Complete an objective at a more difficult settlement while keeping the operation controlled from insertion to extraction.',EXP_PLUS,'challenge'),
    task('surface-team-roles','Assign surface roles','Run a team settlement mission with clear roles for access, overwatch, objective work, and extraction.',EXP_PLUS,'challenge','group'),
    task('surface-lead','Lead a surface op','Brief and lead another Mongrel through a complete on-foot operation, including contingency and extraction plans.',VET,'challenge','group'),
  ],
  mining:[
    task('mining-prospector-check','Prospector discipline','Mine a session where every asteroid you work is prospected first and deliberately compare good rocks with bad ones.',ALL,'activity'),
    task('mining-collector-mode','Collector mode check','Launch collectors with no collectible targeted and run a full mining session without accidentally putting them into single-item mode.',ALL,'challenge'),
    task('mining-50t','Quick fifty-tonne run','Mine and sell at least 50 tonnes from start to finish without turning it into an all-night session.',ALL,'activity'),
    task('mining-hotspot-compare','Compare two hotspot drops','Drop into two different parts of a hotspot and compare how quickly you find worthwhile asteroids.',ALL,'challenge'),
    task('mining-refinery-clean','Keep the refinery clean','Use the ignore list and refinery management so unwanted fragments do not clog the collection loop.',ALL,'challenge'),
    task('mining-position','Mine from a better position','Practice positioning the cargo hatch close to the fragment cloud so collectors spend less time travelling.',ALL,'challenge'),
    task('mining-market-check','Check the market before filling','Choose the commodity and sale destination before mining, then complete a haul sized for the actual market you found.',ALL,'activity'),
    task('mining-core-three','Three efficient cores','Crack three cores while focusing on charge placement and time-to-collection rather than simply finding five eventually.',DEV_PLUS,'challenge'),
    task('mining-subsurface-run','Subsurface session','Complete a session centered on subsurface deposits and practice release timing until it improves.',DEV_PLUS,'challenge'),
    task('mining-controller-test','Test your limpet layout','Change collector/prospector capacity on one mining build and compare whether the bottleneck is extraction or collection.',DEV_PLUS,'challenge'),
    task('mining-yield-test','Compare prospectors','Run a controlled comparison of two prospector-controller choices and record whether the usable yield changes.',EXP_PLUS,'challenge'),
    task('mining-speed-loop','Time the whole loop','Time a complete mine-to-sale loop, identify the slowest stage, and improve that stage on the next run.',EXP_PLUS,'challenge'),
    task('mining-lead-wing','Lead a mining wing','Choose site, commodity, sale plan, and roles for a small Mongrel mining session and lead it through sale.',VET,'challenge','group'),
  ],
  trade:[
    task('trade-two-way','Make the return trip pay','Complete a two-way trade where both the outbound and return leg carry profitable cargo.',ALL,'activity'),
    task('trade-freshness','Reject stale data','Compare at least three market options and deliberately reject one attractive route because its data is too old or supply is too thin.',ALL,'challenge'),
    task('trade-pad-check','Check the pad first','Plan and complete a profitable haul after verifying that both stations support your ship’s landing-pad size.',ALL,'activity'),
    task('trade-supply-depth','Respect the supply','Choose a trade route with enough real supply for several loads and confirm it still works after the first run.',ALL,'challenge'),
    task('trade-profit-log','Track actual profit','Record purchase cost, sale value, tonnage, and actual profit for three legs instead of relying on the advertised route number.',ALL,'activity'),
    task('trade-short-loop','Build a short loop','Create a profitable loop with minimal supercruise and docking time, then run it three times.',ALL,'challenge'),
    task('trade-market-scout','Scout one market','Visit a market that is not currently in your usual route and decide whether its prices, demand, and access make it useful.',ALL,'activity'),
    task('trade-triangle','Three-stop triangle','Build and run a three-station trade triangle where every leg carries useful cargo.',DEV_PLUS,'challenge'),
    task('trade-rare-circuit','Rare-goods circuit','Run a short rare-commodity circuit and pay attention to allocation, distance, and restock behavior.',DEV_PLUS,'challenge'),
    task('trade-compare-routes','Compare profit per hour','Run two different routes for a controlled period and compare real profit per hour rather than profit per trip.',DEV_PLUS,'challenge'),
    task('trade-carrier-arb','Carrier arbitrage run','Use a fleet carrier as part of a profitable buy/load/unload/sell chain and verify every price before committing volume.',EXP_PLUS,'challenge'),
    task('trade-volatility','Trade a changing market','Work a market where price or supply is moving and adjust the route when the original opportunity weakens.',EXP_PLUS,'challenge'),
    task('trade-lead-convoy','Lead a haul group','Organize at least one other Mongrel around a profitable or squad-useful route and keep everyone supplied with current route information.',VET,'challenge','group'),
  ],
  'carrier-logistics':[
    task('carrier-access-check','Check carrier access','Before hauling, verify carrier docking access, market orders, pad suitability, and the intended commodity.',ALL,'activity'),
    task('carrier-250trit','Quarter-load Tritium','Deliver at least 250 tonnes of Tritium to a carrier and verify it reached the intended storage or fuel workflow.',ALL,'activity'),
    task('carrier-market-order','Read the order first','Use an existing carrier buy or sell order correctly and confirm the actual remaining demand/supply after your run.',ALL,'activity'),
    task('carrier-shuttle','Short shuttle loop','Complete three carrier-to-station or station-to-carrier cargo shuttles while minimizing turnaround time.',ALL,'activity'),
    task('carrier-capacity','Watch capacity','Before a large load, check carrier cargo capacity and ensure the planned commodity will actually fit.',ALL,'challenge'),
    task('carrier-services','Service check','Inspect a carrier and identify which installed services matter for the planned operation before relying on it as a base.',ALL,'activity'),
    task('carrier-jump-prep','Prepare one jump','Before a carrier jump, verify destination, Tritium, cargo objective, and what the haulers need after arrival.',ALL,'challenge'),
    task('carrier-fuel-calc','Fuel estimate','Estimate the Tritium requirement for a multi-jump carrier movement and compare your estimate with the actual consumption.',DEV_PLUS,'challenge'),
    task('carrier-flow','Improve loading flow','Run several carrier shuttles and deliberately reduce docking, market, or supercruise dead time between the first and last load.',DEV_PLUS,'challenge'),
    task('carrier-order-plan','Set a logistics price','For a controlled squad operation, calculate a sensible carrier buy/sell price that makes hauling easy without creating accidental losses.',DEV_PLUS,'challenge'),
    task('carrier-contingency','Plan the bad jump','Build a carrier route with a realistic fallback for low Tritium, inaccessible systems, or a changed destination.',EXP_PLUS,'challenge'),
    task('carrier-multihauler','Multi-hauler load','Coordinate at least two haulers loading or unloading the same carrier and keep the operation from duplicating or starving work.',EXP_PLUS,'challenge','group'),
    task('carrier-commander','Command a carrier op','Run a complete carrier movement or cargo operation from briefing through final accounting and debrief.',VET,'challenge','group'),
  ],
  engineering:[
    task('eng-pin-check','Use a pinned blueprint','Verify one useful blueprint is pinned, then perform a remote upgrade and note what still requires an Engineer visit.',ALL,'activity'),
    task('eng-trader','Use a material trader','Trade materials to fill a real engineering shortage instead of farming every missing material directly.',ALL,'activity'),
    task('eng-one-goal','Engineer for one purpose','Pick one problem on a ship—heat, power, jump range, durability, speed, or capacitor—and engineer one module specifically to solve it.',ALL,'activity'),
    task('eng-power-priority','Set power priorities','Configure module power priorities so the ship degrades sensibly if the power plant is damaged or output is limited.',ALL,'challenge'),
    task('eng-weight-check','Find dead weight','Review one ship and remove or justify every module that adds mass without serving the ship’s actual role.',ALL,'challenge'),
    task('eng-experimental-why','Explain the experimental','Install or review one experimental effect and explain the exact reason it belongs on that module.',ALL,'challenge'),
    task('eng-material-plan','Plan before farming','Create a short material shopping list for the next engineering session before gathering anything.',ALL,'activity'),
    task('eng-thermal-vs-raw','Compare two blueprints','Choose a module with two plausible blueprints and compare the finished ship statistics before committing.',DEV_PLUS,'challenge'),
    task('eng-distributor-test','Distributor test','Change or simulate one distributor engineering choice and test whether boost cadence or weapon uptime actually improves.',DEV_PLUS,'challenge'),
    task('eng-powerplant-choice','Power plant tradeoff','Compare Armoured and Overcharged on a real build and choose based on power margin, heat, mass, and integrity.',DEV_PLUS,'challenge'),
    task('eng-fullbuild-audit','Full-build audit','Review a fully engineered ship for power, heat, resistances, jump range, boost, and role fit instead of judging modules separately.',EXP_PLUS,'challenge'),
    task('eng-niche-build','Build for a niche','Design an engineered ship around a narrow purpose and deliberately accept tradeoffs that would be bad on a generalist build.',EXP_PLUS,'challenge'),
    task('eng-mentor-plan','Mentor an engineering plan','Help another Mongrel build an engineering roadmap with priorities, materials, experimentals, and stopping points.',VET,'challenge','group'),
  ],
  exploration:[
    task('explore-honk-fss-dss','Honk, FSS, DSS','Run a short exploration session where you deliberately use Discovery Scanner, FSS, and DSS for their correct jobs instead of skipping straight to the next jump.',ALL,'activity'),
    task('explore-scoop-plan','Scoopable route check','Plot a route, verify fuel-star coverage, and complete it without reaching an emergency fuel state.',ALL,'activity'),
    task('explore-300loop','Three-hundred-light-year loop','Plan and complete a roughly 300-light-year loop that returns somewhere useful instead of just flying outward.',ALL,'activity'),
    task('explore-map-value','Map selectively','In ten systems, decide which bodies are worth mapping and explain why you skipped the rest.',ALL,'challenge'),
    task('explore-offlane','Leave the traffic lane','Move away from a common route or obvious destination line and search for less-traveled systems.',ALL,'challenge'),
    task('explore-surface-stop','Make one surface stop','Include a planetary landing or surface point of interest in an exploration session and return to orbit cleanly.',ALL,'activity'),
    task('explore-return-safe','Return with the data','Complete an exploration outing with a deliberate safe return and sell the data instead of treating arrival as an afterthought.',ALL,'activity'),
    task('explore-neutron-one','One clean neutron boost','Perform a controlled neutron supercharge and make the boosted jump without damaging the ship through a bad cone exit.',DEV_PLUS,'challenge'),
    task('explore-route-filters','Use route filters','Build two versions of the same route using different map filters and compare jump count, fuel risk, and discoveries.',DEV_PLUS,'challenge'),
    task('explore-firstmap','Earn a first mapping','Deliberately search off-route until you earn at least one first-mapped body if the region allows it.',DEV_PLUS,'challenge'),
    task('explore-neutron-chain','Neutron chain','Complete a longer route using multiple neutron boosts while monitoring FSD health and repair needs.',EXP_PLUS,'challenge'),
    task('explore-sparse','Sparse-space planning','Plan and execute a route where jump range and fuel-star spacing require more care than ordinary Bubble travel.',EXP_PLUS,'challenge'),
    task('explore-expedition-lead','Lead an expedition leg','Choose a destination, safety plan, and interesting stops and lead at least one other Mongrel through the route.',VET,'challenge','group'),
  ],
  exobiology:[
    task('exo-dss-heatmap','Read the heatmap','Use the DSS biological filter to choose a landing area and verify whether the terrain actually suits the genus you are hunting.',ALL,'activity'),
    task('exo-one-complete','One clean sample','Find one biological species and complete all required genetic samples without losing track of the organism or spacing.',ALL,'activity'),
    task('exo-spacing','Practice sample spacing','Deliberately pay attention to colony/sample spacing on three species and learn how far you really need to move.',ALL,'challenge'),
    task('exo-terrain-choice','Choose better terrain','For one biological signal, compare two terrain types and decide where the organism is actually easier to locate and land near.',ALL,'challenge'),
    task('exo-lowflight','Low-flight survey','Use low-altitude ship or SRV movement to search efficiently for a species instead of landing at the first visible specimen.',ALL,'activity'),
    task('exo-value-check','Check the value','Before cashing in, identify which sampled species were actually valuable and which were mainly practice.',ALL,'activity'),
    task('exo-footfall','First-footfall attempt','Search away from heavy traffic and try to earn a first footfall while completing at least one biological sample.',ALL,'challenge'),
    task('exo-three-genus','Three-genus session','Complete samples from three different genera and compare which terrain/search patterns worked best.',DEV_PLUS,'challenge'),
    task('exo-landing-efficiency','Landing efficiency','Complete several biological samples while deliberately reducing long walks and repeated takeoff/landing mistakes.',DEV_PLUS,'challenge'),
    task('exo-route-value','Value-focused route','Plan a short route around likely high-value exobiology rather than following random biological signals.',DEV_PLUS,'challenge'),
    task('exo-difficult-terrain','Difficult-terrain sample','Complete a valuable biological sample on terrain that makes landing or visibility difficult without wrecking the ship or wasting excessive time.',EXP_PLUS,'challenge'),
    task('exo-combo-expedition','Bio-exploration loop','Run a multi-system outing where first discoveries, mapping, first footfalls, and exobiology all contribute meaningfully.',EXP_PLUS,'challenge'),
    task('exo-field-lead','Lead a bio outing','Take another Mongrel into the field and teach efficient planet selection, terrain reading, landing, and sample spacing.',VET,'challenge','group'),
  ],
  bgs:[
    task('bgs-controller-check','Identify the controller','Open a live Mongrel system and identify the controlling faction, current influence picture, and state before doing any work.',ALL,'activity'),
    task('bgs-one-order','Do exactly one order','Choose one current Daily Order, complete a meaningful contribution, and stop before freelancing into unrelated activity.',ALL,'activity'),
    task('bgs-beneficiary','Confirm the beneficiary','Before turning in a mission, bounty, trade, or data action, confirm which faction the action will actually support.',ALL,'challenge'),
    task('bgs-stop-condition','Read the stop condition','For one Daily Order, identify both what the squad wants done and the condition that should make you stop.',ALL,'challenge'),
    task('bgs-before-after','Take a before snapshot','Record the current influence/state picture before working a system so you can compare it after the next tick.',ALL,'activity'),
    task('bgs-conflict-check','Check for conflict rules','Before acting in a system, determine whether War/Election or another special condition changes which activities matter.',ALL,'challenge'),
    task('bgs-no-freelance','Avoid the wrong good deed','Find one activity that would normally seem helpful but would be wrong for a current live objective, and explain why you are not doing it.',ALL,'challenge'),
    task('bgs-mix-levers','Use two approved levers','For a current positive influence objective, use two different approved activity types and record what you did.',DEV_PLUS,'challenge'),
    task('bgs-faction-floor','Protect a floor','Review a live system with a faction near a strategic floor and identify which actions could accidentally push it the wrong way.',DEV_PLUS,'challenge'),
    task('bgs-tick-note','Write a tick note','After a tick, compare expected versus actual change and write one useful observation for future work.',DEV_PLUS,'challenge'),
    task('bgs-saturation-test','Stop before saturation','Run a measured BGS session with a pre-set effort limit, then stop and use the next tick to judge whether more work was actually needed.',EXP_PLUS,'challenge'),
    task('bgs-diagnose-state','Diagnose a state plan','Choose one strategic system and explain how its current states, pending states, influence bands, and control interact with the squad objective.',EXP_PLUS,'challenge'),
    task('bgs-lead-brief','Lead a BGS brief','Explain a live BGS objective to other Mongrels with beneficiary, allowed actions, forbidden actions, and stopping conditions.',VET,'challenge','group'),
  ],
  colonization:[
    task('colony-requirements','Read the build requirements','Visit or review an active construction site and identify what it actually needs before hauling anything.',ALL,'activity'),
    task('colony-250t','Quarter-load construction','Deliver at least 250 tonnes of a currently useful construction commodity to an active project.',ALL,'activity'),
    task('colony-pad-check','Check the landing access','Before sourcing cargo, verify the construction destination can accept the ship you plan to use.',ALL,'challenge'),
    task('colony-source-market','Find a real source','Find a source market with enough supply for the planned construction run instead of choosing only the lowest advertised price.',ALL,'activity'),
    task('colony-progress-check','Check progress before hauling','Verify the current remaining requirement immediately before starting a construction haul.',ALL,'activity'),
    task('colony-site-tour','Tour two sites','Visit two different sites in a developing colony system and compare their purpose, location, and logistics needs.',ALL,'activity'),
    task('colony-full-cycle','Complete a construction cycle','Source cargo, haul it, deliver it, and verify the project progress changed before ending the session.',ALL,'activity'),
    task('colony-load-estimate','Estimate remaining loads','Convert one remaining construction requirement into approximate shiploads for the hauler you actually use.',DEV_PLUS,'challenge'),
    task('colony-source-compare','Compare two sources','Compare two source markets using supply, pad access, distance, and turnaround time rather than price alone.',DEV_PLUS,'challenge'),
    task('colony-carrier-shuttle','Carrier staging loop','Use a carrier as a staging point for several construction shuttles and judge whether it improved total throughput.',DEV_PLUS,'challenge','group'),
    task('colony-multisite','Multi-site logistics','Support more than one active site in a single planned session without delivering cargo to the wrong requirement.',EXP_PLUS,'challenge'),
    task('colony-throughput','Optimize tonnes per hour','Measure a construction hauling loop, identify the bottleneck, and improve real tonnes delivered per hour.',EXP_PLUS,'challenge'),
    task('colony-lead-push','Lead a construction push','Brief a build requirement, organize at least one other Mongrel, and run the hauling effort to a clear milestone.',VET,'challenge','group'),
  ],
  powerplay:[
    task('pp-current-goal','Check the current objective','Before doing Powerplay work, identify what your chosen activity is meant to accomplish and where that objective is currently relevant.',ALL,'activity'),
    task('pp-one-loop','Complete one full loop','Run one Powerplay activity from preparation through turn-in so you understand the complete cycle.',ALL,'activity'),
    task('pp-ship-fit','Fit for the activity','Choose or adjust a ship specifically for the Powerplay activity you plan to perform, then test the result.',ALL,'challenge'),
    task('pp-timebox','Time-box the session','Run a focused 30-minute Powerplay session and stop to evaluate efficiency instead of grinding automatically.',ALL,'activity'),
    task('pp-map-read','Read the strategic map','Choose a Powerplay location and explain what makes it relevant before travelling there.',ALL,'challenge'),
    task('pp-merit-check','Track the reward','Complete a Powerplay activity and verify how the result or merits were credited rather than assuming the action counted.',ALL,'activity'),
    task('pp-two-methods','Try two methods','Complete two different Powerplay activities and compare which better fits your ship and play style.',ALL,'challenge'),
    task('pp-route-efficiency','Improve the route','Repeat a Powerplay logistics or combat loop and deliberately reduce dead travel or turnaround time.',DEV_PLUS,'challenge'),
    task('pp-build-specialist','Specialize a build','Tune one ship around a specific Powerplay activity instead of using a generic multipurpose loadout.',DEV_PLUS,'challenge'),
    task('pp-context-check','Check before repeating','Before repeating yesterday’s Powerplay work, verify that the same location and activity are still useful today.',DEV_PLUS,'challenge'),
    task('pp-team-objective','Team objective','Coordinate with another Commander on the same Powerplay objective and divide roles instead of duplicating effort.',EXP_PLUS,'challenge','group'),
    task('pp-efficiency-log','Measure merits per hour','Track one Powerplay method for a full session and compare its real output per hour with another method you know.',EXP_PLUS,'challenge'),
    task('pp-lead-session','Lead a Powerplay session','Choose a useful objective, brief the activity and route, and lead at least one other Mongrel through the session.',VET,'challenge','group'),
  ],
  operations:[
    task('ops-check-orders','Check orders before launching','Before leaving port, review current Daily Orders and choose one task that matches your ship and available time.',ALL,'activity'),
    task('ops-escort-help','Answer an escort request','Join a posted escort or protection request and stay with the stated objective until the requester is safe or finished.',ALL,'activity','group'),
    task('ops-event-join','Join one squad event','Participate in a current squad event or organized activity and stay through the agreed stopping point.',ALL,'activity','group'),
    task('ops-report-result','Report the useful result','After completing squad work, report what was accomplished with enough detail that leadership can act on it.',ALL,'activity'),
    task('ops-switch-role','Fill the missing role','Join a squad activity in a support role you do not normally choose—escort, scout, logistics, repair, or coordination.',ALL,'challenge','group'),
    task('ops-help-new','Help one Mongrel','Spend part of a session solving another member’s actual problem rather than only giving them a link or build list.',ALL,'activity','group'),
    task('ops-preflight','Preflight an operation','Before joining current tasking, verify ship, fuel, limpets/ammunition, destination, and rebuy so you do not become the delay.',ALL,'challenge'),
    task('ops-scout-report','Scout and report','Scout a requested system or location and return a concise report that answers the operational question leadership actually asked.',DEV_PLUS,'challenge'),
    task('ops-coordinate-two','Coordinate two people','Take a small squad need and organize at least one other member so the work is divided rather than duplicated.',DEV_PLUS,'challenge','group'),
    task('ops-afteraction','Write a short AAR','After a squad operation, record what worked, what failed, and one concrete improvement for the next run.',DEV_PLUS,'challenge'),
    task('ops-multirole','Run a multi-role task','Join an operation where combat, scouting, hauling, or support roles must work together and deliberately stay inside your assigned role.',EXP_PLUS,'challenge','group'),
    task('ops-contingency','Plan the fallback','Before leading or joining a meaningful operation, identify the likely failure point and agree on a fallback plan.',EXP_PLUS,'challenge','group'),
    task('ops-duty-lead','Duty lead','Take one current squad objective, turn it into a clear brief, organize the people needed, and close the loop with a result report.',VET,'challenge','group'),
  ],
};

export function getEligibleStartTasks(activity, experience = 'new', playStyle = 'either') {
  const pool = [...(Array.isArray(START_TASKS[activity]) ? START_TASKS[activity] : []), ...(Array.isArray(START_TASK_ADDITIONS[activity]) ? START_TASK_ADDITIONS[activity] : [])];
  const levelPool = pool.filter(item => Array.isArray(item.levels) && item.levels.includes(experience));
  const stylePreferred = levelPool.filter(item => !(playStyle === 'solo' && item.style === 'group'));
  const selected = stylePreferred.length >= DAILY_TASK_LIMIT ? stylePreferred : levelPool;
  return selected.map(item => ({ ...item, link:item.link || START_ACTIVITY_META[activity]?.link || '/activities/' }));
}
